export default {
  SET_LOCAL_STORAGE_UPDATE_DATE: 'SET_LOCAL_STORAGE_UPDATE_DATE',
  FETCH_WARRIORS_REQUESTED: 'FETCH_WARRIORS_REQUESTED',
  FETCH_WARRIORS_SUCCEEDED: 'FETCH_WARRIORS_SUCEEDED',
  FETCH_WARRIORS_FAILED: 'FETCH_WARRIORS_FAILED',
  ADD_WARRIOR_TO_MY_LIST: 'ADD_WARRIOR_TO_MY_LIST',
  REMOVE_WARRIOR_FROM_MY_LIST: 'REMOVE_WARRIOR_FROM_MY_LIST',
  REMOVE_WARRIOR: 'REMOVE_WARRIOR',
  ADD_WARRIOR: 'ADD_WARRIOR',
};
